const busDetailsData = {
    1: {
      id:1,  
      columns: 3,
      source:'SOMANUR',
      busRoute: "Somanur BS - Karumatham Patti - Kaaduvettipalayam Annur - Puliyampatti",

      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    2: {
        id:2,  
      columns: 3,
      source: "Tiruppur (Kumaran College)",
    busRoute: "S R Nagar - Railway Station - Puspha Theatre - Kumar Nagar - Anuppar Palayam - Avinashi - P.Puliyampatti",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    3: {
        id:3, 
      columns: 3,
      source: "Tiruppur (Old Bus Stand)",
    busRoute: "Nataraj Theater - Railway Station - Puspa Theatre - Anupparpalayam - Avinashi - P.Puliyampatti",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    4: {
        id:4, 
      columns: 3,
      source: "Tiruppur (New Bus Stand)",
    busRoute: "Perumanallur - Malayappalayam - Nambiyur - Kurumandur - Makkianam Kombai - Arasur",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    5: {
        id:5, 
      columns: 3,
      source: "Avinashi",
    busRoute: "Avinashi Old & New BS - Sevur - P.Puliyampatti",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    6: {
        id:6, 
      columns: 3,
      source: "Saravanampatti / Kovil Palayam / Annur",
    busRoute: "Kovil Palayam - Annur - P.Puliyampatti",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    7: {
        id:7, 
      columns: 3,
      source: "Thudiyalur / Periyanaicken Palayam",
    busRoute: "Periyanaicken Palayam - Veerapandi Pirivu - Karamadai - Mettupalayam - Sirumugai",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    8: {
        id:8, 
      columns: 3,
      source: "Mettupalayam / Sirumugai",
    busRoute: "Alankombu - Sirumugai - Pethikuttai",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    9: {
        id:9, 
      columns: 3,
      source: "Karamadai",
      busRoute: "Mettupalayam - Alankombu - Sirumugai - Pethikuttai",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    10: {
        id:10, 
      columns: 3,
      source: "Erode / Chitode / Kavindapadii",
    busRoute: "Chitode - Kavindapadi - Gobichettipalayam - Kasipalayam - Arasur",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    11: {
        id:11, 
      columns: 3,
      source: "Perundurai",
    busRoute: "Mettupalayam - Alankombu - Sirumugai - Pethikuttai",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    12: {
        id:12, 
      columns: 3,
      source: "Karamadai",
    busRoute: "Thudupathi - Thingalur - Siruvalur - Kolappalur - Kurumandur - Makkianam Kombai - Arasur",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    13: {
        id:13, 
      columns: 3,
      source: "Komarapalayam (Bhavani)",
    busRoute: "Komarapalayam Bus Stand – Bhavani New BS – Anthiyur Corner – Jambai – Appakoodal - Athani",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
    14: {
        id:14, 
      columns: 3,
      source: "Sathyamangalam Town",
    busRoute: "Gandhi Nagar - SRT Corner - Rangasamuthiram - Bus Stand - Northpet",
      data: {
        column1: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column2: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
        column3: {
          busNo:"Bus 001",
          driver: "John Doe",
          conductor: "Jane Smith",
          totalSeats: 50,
          seatsAllocated: 40,
          vacancy: 10,
        },
      },
    },
  };
  
  export default busDetailsData;
  