const studentsData = [
  { id: 1, name: "Alice", gender: "Female", busSource: "Somanur BS", busNo: "Bus 001" },
  { id: 2, name: "Bob", gender: "Male", busSource: "S R Nagar", busNo: "Bus 002" },
  { id: 3, name: "Charlie", gender: "Male", busSource: "Tiruppur (Old Bus Stand)", busNo: "Bus 003" },
  { id: 4, name: "Diana", gender: "Female", busSource: "Tiruppur (New Bus Stand)", busNo: "Bus 004" },
  { id: 5, name: "Eve", gender: "Female", busSource: "Avinashi", busNo: "Bus 005" },
  { id: 6, name: "Frank", gender: "Male", busSource: "Saravanampatti / Kovil Palayam / Annur", busNo: "Bus 006" },
  { id: 7, name: "Grace", gender: "Female", busSource: "Thudiyalur / Periyanaicken Palayam", busNo: "Bus 007" },
  { id: 8, name: "Hank", gender: "Male", busSource: "Mettupalayam / Sirumugai", busNo: "Bus 008" },
  { id: 9, name: "Ivy", gender: "Female", busSource: "Karamadai", busNo: "Bus 009" },
  { id: 10, name: "Jack", gender: "Male", busSource: "Erode / Chitode / Kavindapadi", busNo: "Bus 010" },
  { id: 11, name: "Karen", gender: "Female", busSource: "Perundurai", busNo: "Bus 011" },
  { id: 12, name: "Leo", gender: "Male", busSource: "Karamadai", busNo: "Bus 012" },
  { id: 13, name: "Mona", gender: "Female", busSource: "Komarapalayam (Bhavani)", busNo: "Bus 013" },
  { id: 14, name: "Nathan", gender: "Male", busSource: "Sathyamangalam Town", busNo: "Bus 014" },
  { id: 15, name: "Olivia", gender: "Female", busSource: "Somanur BS", busNo: "Bus 001" },
  { id: 16, name: "Paul", gender: "Male", busSource: "S R Nagar", busNo: "Bus 002" },
  { id: 17, name: "Quinn", gender: "Female", busSource: "Tiruppur (Old Bus Stand)", busNo: "Bus 003" },
  { id: 18, name: "Rachel", gender: "Female", busSource: "Tiruppur (New Bus Stand)", busNo: "Bus 004" },
  { id: 19, name: "Steve", gender: "Male", busSource: "Avinashi", busNo: "Bus 005" },
  { id: 20, name: "Tina", gender: "Female", busSource: "Saravanampatti / Kovil Palayam / Annur", busNo: "Bus 006" },
  { id: 21, name: "Uma", gender: "Female", busSource: "Thudiyalur / Periyanaicken Palayam", busNo: "Bus 007" },
  { id: 22, name: "Victor", gender: "Male", busSource: "Mettupalayam / Sirumugai", busNo: "Bus 008" },
  { id: 23, name: "Wendy", gender: "Female", busSource: "Karamadai", busNo: "Bus 009" },
  { id: 24, name: "Xander", gender: "Male", busSource: "Erode / Chitode / Kavindapadi", busNo: "Bus 010" },
  { id: 25, name: "Yara", gender: "Female", busSource: "Perundurai", busNo: "Bus 011" },
  { id: 26, name: "Zach", gender: "Male", busSource: "Karamadai", busNo: "Bus 012" },
  { id: 27, name: "Amber", gender: "Female", busSource: "Komarapalayam (Bhavani)", busNo: "Bus 013" },
  { id: 28, name: "Brian", gender: "Male", busSource: "Sathyamangalam Town", busNo: "Bus 014" },
  { id: 29, name: "Cathy", gender: "Female", busSource: "Somanur BS", busNo: "Bus 001" },
  { id: 30, name: "David", gender: "Male", busSource: "S R Nagar", busNo: "Bus 002" },
  { id: 31, name: "Ella", gender: "Female", busSource: "Tiruppur (Old Bus Stand)", busNo: "Bus 003" },
  { id: 32, name: "Felix", gender: "Male", busSource: "Tiruppur (New Bus Stand)", busNo: "Bus 004" },
  { id: 33, name: "Gina", gender: "Female", busSource: "Avinashi", busNo: "Bus 005" },
  { id: 34, name: "Harry", gender: "Male", busSource: "Saravanampatti / Kovil Palayam / Annur", busNo: "Bus 006" },
  { id: 35, name: "Iris", gender: "Female", busSource: "Thudiyalur / Periyanaicken Palayam", busNo: "Bus 007" },
  { id: 36, name: "James", gender: "Male", busSource: "Mettupalayam / Sirumugai", busNo: "Bus 008" },
  { id: 37, name: "Kara", gender: "Female", busSource: "Karamadai", busNo: "Bus 009" },
  { id: 38, name: "Liam", gender: "Male", busSource: "Erode / Chitode / Kavindapadi", busNo: "Bus 010" },
  { id: 39, name: "Maya", gender: "Female", busSource: "Perundurai", busNo: "Bus 011" },
  { id: 40, name: "Noah", gender: "Male", busSource: "Karamadai", busNo: "Bus 012" },
  { id: 41, name: "Olga", gender: "Female", busSource: "Komarapalayam (Bhavani)", busNo: "Bus 013" },
  { id: 42, name: "Peter", gender: "Male", busSource: "Sathyamangalam Town", busNo: "Bus 014" },
  { id: 43, name: "Quincy", gender: "Male", busSource: "Somanur BS", busNo: "Bus 001" },
  { id: 44, name: "Rita", gender: "Female", busSource: "S R Nagar", busNo: "Bus 002" },
  { id: 45, name: "Sam", gender: "Male", busSource: "Tiruppur (Old Bus Stand)", busNo: "Bus 003" },
  { id: 46, name: "Tara", gender: "Female", busSource: "Tiruppur (New Bus Stand)", busNo: "Bus 004" },
  { id: 47, name: "Ursula", gender: "Female", busSource: "Avinashi", busNo: "Bus 005" },
  { id: 48, name: "Vince", gender: "Male", busSource: "Saravanampatti / Kovil Palayam / Annur", busNo: "Bus 006" },
  { id: 49, name: "Willa", gender: "Female", busSource: "Thudiyalur / Periyanaicken Palayam", busNo: "Bus 007" },
  { id: 50, name: "Xenia", gender: "Female", busSource: "Mettupalayam / Sirumugai", busNo: "Bus 008" },
];

export default studentsData;
